apply plugin: 'com.android.application'

configurations.all {
    exclude group: 'com.intellij', module: 'annotations'
}

android {
    compileSdk 35

    packaging {
        resources {
            excludes += ['META-INF/DEPENDENCIES', 'META-INF/LICENSE', 'META-INF/LICENSE.txt', 'META-INF/NOTICE', 'META-INF/NOTICE.txt']
        }
    }
    // buildToolsVersion is managed by AGP

    namespace 'io.github.javiewer'

    defaultConfig {
        applicationId "io.github.javiewer"
        minSdkVersion 21
        targetSdkVersion 35
        versionCode 18
        versionName "2.1.1"

        ndk {
            abiFilters "arm64-v8a"
        }
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    //Support
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'androidx.cardview:cardview:1.0.0'
    implementation 'com.google.android.material:material:1.12.0'
    implementation 'androidx.palette:palette:1.0.0'
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    implementation 'androidx.percentlayout:percentlayout:1.0.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.2.0'
    //View
    implementation "com.mikepenz:materialdrawer:6.1.2"
    implementation 'com.aurelhubert:ahbottomnavigation:2.2.0'
    implementation 'com.wefika:flowlayout:0.4.1'
    implementation 'de.hdodenhof:circleimageview:3.1.0'
    implementation 'com.flaviofaria:kenburnsview:1.0.7'
    //Utility
    implementation 'cat.ereza:customactivityoncrash:2.2.0'
    implementation 'com.github.bumptech.glide:glide:4.16.0'
    implementation 'com.google.code.gson:gson:2.11.0'
    implementation 'com.squareup.retrofit2:converter-gson:2.11.0'
    implementation 'com.squareup.retrofit2:retrofit:2.11.0'
    implementation 'org.jsoup:jsoup:1.18.3'
    implementation 'com.karumi:dexter:6.2.2'
    implementation 'jp.wasabeef:recyclerview-animators:4.0.2'

    //Player
    implementation 'cn.jzvd:jiaozivideoplayer:6.2.12'
    implementation 'com.google.android.exoplayer:exoplayer:2.19.1'

    testImplementation 'junit:junit:4.13.2'
}
